### ISSUE TITLE
Error while trying to install package pyhepmc-ng

### ISSUE THREAD

**Issue by Kieran-Mg1** [jacanchaplais/heparchy#15]
Running `pip install heparchy` produces the following error on MacOS version 12.3.1 with Apple M1 Pro chip:

Building wheels for collected packages: pyhepmc-ng
  Building wheel for pyhepmc-ng (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-cpython-38
      creating build/lib.macosx-10.9-x86_64-cpython-38/pyhepmc_ng
      copying src/pyhepmc_ng/_version.py -> build/lib.macosx-10.9-x86_64-cpython-38/pyhepmc_ng
      copying src/pyhepmc_ng/_io.py -> build/lib.macosx-10.9-x86_64-cpython-38/pyhepmc_ng
      copying src/pyhepmc_ng/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-38/pyhepmc_ng
      copying src/pyhepmc_ng/view.py -> build/lib.macosx-10.9-x86_64-cpython-38/pyhepmc_ng
      running build_ext
      building 'pyhepmc_ng._bindings' extension
      creating build/temp.macosx-10.9-x86_64-cpython-38
      creating build/temp.macosx-10.9-x86_64-cpython-38/extern
      creating build/temp.macosx-10.9-x86_64-cpython-38/extern/HepMC3
      creating build/temp.macosx-10.9-x86_64-cpython-38/extern/HepMC3/src
      creating build/temp.macosx-10.9-x86_64-cpython-38/src
      error: [Errno 2] No such file or directory: 'x86_64-apple-darwin13.4.0-clang'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyhepmc-ng
  Running setup.py clean for pyhepmc-ng
Failed to build pyhepmc-ng
Installing collected packages: pyhepmc-ng, h5py, heparchy
  Running setup.py install for pyhepmc-ng ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pyhepmc-ng did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      running install
      /Users/kieran/opt/anaconda3/envs/tree_extractor/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-cpython-38
      creating build/lib.macosx-10.9-x86_64-cpython-38/pyhepmc_ng
      copying src/pyhepmc_ng/_version.py -> build/lib.macosx-10.9-x86_64-cpython-38/pyhepmc_ng
      copying src/pyhepmc_ng/_io.py -> build/lib.macosx-10.9-x86_64-cpython-38/pyhepmc_ng
      copying src/pyhepmc_ng/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-38/pyhepmc_ng
      copying src/pyhepmc_ng/view.py -> build/lib.macosx-10.9-x86_64-cpython-38/pyhepmc_ng
      running build_ext
      building 'pyhepmc_ng._bindings' extension
      creating build/temp.macosx-10.9-x86_64-cpython-38
      creating build/temp.macosx-10.9-x86_64-cpython-38/extern
      creating build/temp.macosx-10.9-x86_64-cpython-38/extern/HepMC3
      creating build/temp.macosx-10.9-x86_64-cpython-38/extern/HepMC3/src
      creating build/temp.macosx-10.9-x86_64-cpython-38/src
      error: [Errno 2] No such file or directory: 'x86_64-apple-darwin13.4.0-clang'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyhepmc-ng

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Versions**
Python: 3.8.13

**Further Information**
`pip install pyhepmc` runs successfully, the authors of  pyhepmc state "The pyhepmc-ng package is continued as the package pyhepmc. Please install pyhepmc, pyhepmc-ng is no longer updated.", perhaps this is the issue?

**Comment by jacanchaplais** [comment]
Thanks for this @Kieran-Mg1! Will test the newly maintained package with the `heparchy.read.hepmc` module. I suspect there will at least be some minor namespace errors if I only change the dependency, but this module does need to be updated to match the HDF5 interface anyway, so some maintenance is in order one way or another.

Will try to get something working online today, but if not will be early next week.

**Comment by jacanchaplais** [comment]
So switching the dependency indeed break that module's functionality in some nontrivial ways, and some time spent working out the differences between the API of `pyhepmc_ng` and `pyhepmc` is necessary. I might just remove the module from the public API while I work on fixing it, and reintroduce it once done.

@Kieran-Mg1 would it be possible for you to see whether installing `pyhepmc-ng==0.4.3` before installing heparchy solves the issue? If so, it could be a short term solution that I could pin in the setup.cfg until I change the implementation of `heparchy.read.hepmc`.

**Comment by Kieran-Mg1** [comment]
@jacanchaplais your suggested solution worked, installing pyhepmc-ng==0.4.3 before installing heparchy produces no error message and heparchy appears to install successfully.

**Comment by Kieran-Mg1** [comment]
Not sure if this is related, but `from heparchy.read.hdf import HdfReader ` produces the error `No module named 'heparchy.read.hdf'; 'heparchy.read' is not a package`. 
When I navigate to where heparchy is installed, listed in the directory is: \__init__.py,	\__pycache__,	\_version.py,	data.py,	hepmc.py,	read.py,		utils.py,	write.py, which I think explains the error.
I installed heparchy with `pip install heparchy`, is this to be expected?

**Comment by jacanchaplais** [comment]
Thanks for pointing this out, I installed it locally in dev mode, and I think Giorgio did too, so we missed that the subpackages need to explicitly be added to the namespace. I've pushed a patch which should fix both of the problems listed here. Could you try installing it with the following:

`pip install git+https://github.com/jacanchaplais/heparchy.git@patch/outdated-deps-15`

If that works I'll merge into the release branch, and bump up the beta version to `heparchy==0.2b2` on PyPI, then you can install that. :)

**Comment by Kieran-Mg1** [comment]
Yes `pip install git+https://github.com/jacanchaplais/heparchy.git@patch/outdated-deps-15` worked correctly, thank you :)

**Comment by jacanchaplais** [comment]
Excellent, built and uploaded to PyPI. :) Thanks for flagging this!
https://pypi.org/project/heparchy/0.2b2/

**Comment by jacanchaplais** [comment]
Hi Kieran, ah that's intentional! It's because `read_event` is deprecated. Now you can simply subscript the process object to get event objects, _eg._

```python
with HdfReader(data_path) as hep_file:
    proc = hep_file.read_process("default")
    event = proc[2]  # explicit subscripting
    for event in proc:  # iteration
        ...
```

The `main` branch should not be used as an up-to-date reference, since it only gets updated when the next major or minor version of the release branch comes out of beta, and gets merged. Until this happens the API should be considered unstable. To be honest, the release branch should be renamed to `release/1.0`, since there are significant API changes. In any case, I really appreciate you looking into the source code! I do highly recommend that you pin yourself to a version officially distributed on PyPI without custom modifications, for your work, though (since this may prevent you getting downstream improvements or bug fixes).

**Comment by jacanchaplais** [comment]
See #16. Added a new release, `heparchy==0.2b3`, which includes the `read_event` method, but adds a deprecation warning to it.
