### ISSUE TITLE
Incompatibility with python 3.7

### ISSUE THREAD

**Issue by GiorgioCerro** [jacanchaplais/heparchy#22]
From version heparchy==0.2b6, when trying to import it I get the following error:
ImportError: cannot import name 'cached_property' from 'functools'

Stackoverflow says that cached_property has been added after python 3.8

**Comment by jacanchaplais** [comment]
Sorry @GiorgioCerro , I only plan to support Python 3.8 and higher, but I will make this more explicit in the build configs so the dependency resolvers catch this.
